name: Pipeline test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the version as needed

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Install required packages
      run: |
        pip install pandas
        pip install numpy
        pip install requests
        pip install sqlalchemy
        pip install unittest2

    - name: Make tests.sh executable
      run: chmod +x tests.sh

    - name: Run tests
      run: project/tests.sh